### ISSUE TITLE
Support older JRE version (8)

### ISSUE THREAD

**Issue by samuelololol** [BigTows/PinNote#25]
Could not run piNote plugin with older version of JRE(8).

**Comment by samuelololol** [comment]
Or any patch I can apply to the source and manually build from scratch?

**Comment by BigTows** [comment]
You have trouble with run Plugin in specific IDEA version? Please specificated it.

Or something else?

**Comment by BigTows** [comment]
Or you can manually rebuild project with gradle.

**Comment by BigTows** [comment]
@samuelololol I am close issues.
