### ISSUE TITLE
[enhancement] plz add support for reorder regroup drag and drop

### ISSUE THREAD

**Issue by ash0080** [BigTows/PinNote#26]
At least the shortcut keys

**Comment by BigTows** [comment]
Hey, great idea's, i will try

**Comment by BigTows** [comment]
Support delete target from shortcut.

**Comment by BigTows** [comment]
Bugs list:

- [ ] Can't delete first task of list.

**Comment by BigTows** [comment]
@ash0080 Hello, i am upload pre-release of upcoming updates. What do you think?

https://github.com/BigTows/PinNote/releases/tag/2.1-b.4

**Comment by BigTows** [comment]
Done. btw thx for idea :)
